version: "3.8"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
